# Auto-increment version and generate VersionInfo.cs
param(
    [string]$Config = "Release",
    [switch]$SkipIncrement
)

$versionFile = "version.txt"
$versionCs = "Source\VersionInfo.cs"

# Read current version
$rawContent = Get-Content $versionFile -Raw
$ver = if ($rawContent) { [decimal]$rawContent.Trim() } else { 0.000 }

# Increment version unless skip flag is set
if (-not $SkipIncrement) {
    $ver += 0.001
    $ver = [Math]::Round($ver, 3)
    # Write back to file
    Set-Content $versionFile $ver.ToString('0.000')
}

# Determine build type
$buildType = if ($Config -eq 'Debug') {'D'} else {'R'}
$versionString = "$ver($buildType)"
$timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'

# Generate VersionInfo.cs
$cs = @"
// Auto-generated by update-version.ps1 - DO NOT EDIT MANUALLY
// Build timestamp: $timestamp
// Build configuration: $Config

namespace SurvivalTools
{
    public static class BuildVersion
    {
        public const string Version = "$versionString";
        public const string VersionNumber = "$ver";
        public const string BuildType = "$buildType";
        public const string BuildConfig = "$Config";
        public const string BuildTimestamp = "$timestamp";
    }
}
"@

Set-Content $versionCs $cs

Write-Host "Version updated to: $versionString"
