// Auto-generated by update-version.ps1 - DO NOT EDIT MANUALLY
// Build timestamp: 2026-04-24 13:27:25
// Build configuration: Debug

namespace SurvivalTools
{
    public static class BuildVersion
    {
        public const string Version = "0.002(D)";
        public const string VersionNumber = "0.002";
        public const string BuildType = "D";
        public const string BuildConfig = "Debug";
        public const string BuildTimestamp = "2026-04-24 13:27:25";
    }
}
