// Auto-generated by update-version.ps1 - DO NOT EDIT MANUALLY
// Build timestamp: 2026-04-26 17:09:25
// Build configuration: Release

namespace SurvivalTools
{
    public static class BuildVersion
    {
        public const string Version = "0.003(R)";
        public const string VersionNumber = "0.003";
        public const string BuildType = "R";
        public const string BuildConfig = "Release";
        public const string BuildTimestamp = "2026-04-26 17:09:25";
    }
}
