// Auto-generated by update-version.ps1 - DO NOT EDIT MANUALLY
// Build timestamp: 2026-04-24 12:58:59
// Build configuration: Debug

namespace SurvivalTools
{
    public static class BuildVersion
    {
        public const string Version = "0.001(D)";
        public const string VersionNumber = "0.001";
        public const string BuildType = "D";
        public const string BuildConfig = "Debug";
        public const string BuildTimestamp = "2026-04-24 12:58:59";
    }
}
